version: "3.8"

services:

  db:
    image: mysql
    container_name: db_docker_api_free
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  phpmyadmin:
    image: phpmyadmin
    container_name: phpMyAdmin_docker_api_free
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db

  www:
    build: php
    container_name: www_docker_api_free
    ports:
      - "8000:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev


networks:
  dev:

volumes:
  db-data: